import "./globals.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
<<<<<<< HEAD
=======
import Footer from "./components/Footer";

>>>>>>> a15dfb163178e1bb47e1274b294a3afbeb368e80

export const metadata = {
  title: "Arrakis AI Ecosystem",
  description: "Generated by AI",
};

const myFont = localFont(
  {
    src: [
      {
        path: '../public/fonts/ClashGrotesk-Extralight.woff2',
        weight: '200',
        style: 'normal',
      },
      {
        path: '../public/fonts/ClashGrotesk-Light.woff2',
        weight: '300',
        style: 'normal',
     },
      {
        path: '../public/fonts/ClashGrotesk-Regular.woff2',
        weight: '400',
        style: 'normal',
      }, 
      {
        path: '../public/fonts/ClashGrotesk-Medium.woff2',
        weight: '500',
        style: 'normal',
      },
      {
        path: '../public/fonts/ClashGrotesk-Semibold.woff2',
        weight: '600',
        style: 'normal',
      }, 
      {
        path: '../public/fonts/ClashGrotesk-Bold.woff2',
        weight: '700',
        style: 'normal',
      }
     
    ],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {children}
      </body>
    </html>
  );
}
